import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { supabaseCmd } from "./lib/supabase-cli";

const envPath = join(process.cwd(), "apps/web/.env.local");

function parseSupabaseEnv(output: string): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const line of output.split("\n")) {
    const match = line.match(/^([A-Z_]+)="(.*)"$/);
    if (match) vars[match[1]!] = match[2]!;
  }
  return vars;
}

function getStatus(workdir?: string): Record<string, string> {
  const cmd = workdir
    ? supabaseCmd(`status -o env --workdir ${workdir}`)
    : supabaseCmd("status -o env");
  return parseSupabaseEnv(execSync(cmd, { encoding: "utf8" }));
}

const meta = getStatus();
const target = getStatus("supabase-target");
const encryptionKey = randomBytes(32).toString("hex");
const setupSecret = randomBytes(32).toString("hex");

const lines = [
  `# Generated by pnpm setup:env-local`,
  `NEXT_PUBLIC_META_SUPABASE_URL=${meta.API_URL ?? "http://127.0.0.1:54321"}`,
  `NEXT_PUBLIC_META_SUPABASE_ANON_KEY=${meta.ANON_KEY ?? ""}`,
  `META_SUPABASE_SERVICE_ROLE_KEY=${meta.SERVICE_ROLE_KEY ?? ""}`,
  `LOCAL_TARGET_SUPABASE_URL=${target.API_URL ?? "http://127.0.0.1:54421"}`,
  `LOCAL_TARGET_SUPABASE_ANON_KEY=${target.ANON_KEY ?? ""}`,
  `LOCAL_TARGET_SUPABASE_SERVICE_ROLE_KEY=${target.SERVICE_ROLE_KEY ?? ""}`,
  `DATABASE_URL=${meta.DB_URL ?? "postgresql://postgres:postgres@127.0.0.1:54322/postgres"}`,
  `TEST_DATABASE_URL=${meta.DB_URL ?? "postgresql://postgres:postgres@127.0.0.1:54322/postgres"}`,
  `ENCRYPTION_KEY=${encryptionKey}`,
  `SETUP_SECRET=${setupSecret}`,
  `NEXT_PUBLIC_APP_URL=http://localhost:3000`,
  ``,
];

writeFileSync(envPath, lines.join("\n"));
console.log(`Wrote ${envPath}`);
